import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from '@/app/common/NavBar'
import Footer from '@/app/common/Footer'


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    < head>
    </head>
    <body className={inter.className}>
      <NavBar></NavBar>
      {children}
      <Footer></Footer>
    </body>
      
    </html>
  );
}
